frame_num: 29 # 合法的 frame_num 值：5, 9, 13, 17, 21, 25, 29, 33(默认), ...                       
motion_frames_latent_num: 2
tgt_fps: 24
sample_rate: 16000
sample_shift: 5
color_correction_strength: 1.0
cached_audio_duration: 8
num_heads: 12
height: 512
width: 512
