// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: asr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscriptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *TranscriptEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptEvent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscriptEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\n" +
	"cyberverse\x1a\fcommon.proto\"|\n" +
	"\x0fTranscriptEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence2Y\n" +
	"\n" +
	"ASRService\x12K\n" +
	"\x10TranscribeStream\x12\x16.cyberverse.AudioChunk\x1a\x1b.cyberverse.TranscriptEvent(\x010\x01B*Z(github.com/cyberverse/server/internal/pbb\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_asr_proto_goTypes = []any{
	(*TranscriptEvent)(nil), // 0: cyberverse.TranscriptEvent
	(*AudioChunk)(nil),      // 1: cyberverse.AudioChunk
}
var file_asr_proto_depIdxs = []int32{
	1, // 0: cyberverse.ASRService.TranscribeStream:input_type -> cyberverse.AudioChunk
	0, // 1: cyberverse.ASRService.TranscribeStream:output_type -> cyberverse.TranscriptEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
