// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: avatar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageFormat   string                 `protobuf:"bytes,3,opt,name=image_format,json=imageFormat,proto3" json:"image_format,omitempty"`
	UseFaceCrop   bool                   `protobuf:"varint,4,opt,name=use_face_crop,json=useFaceCrop,proto3" json:"use_face_crop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvatarRequest) Reset() {
	*x = SetAvatarRequest{}
	mi := &file_avatar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvatarRequest) ProtoMessage() {}

func (x *SetAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvatarRequest.ProtoReflect.Descriptor instead.
func (*SetAvatarRequest) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *SetAvatarRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetAvatarRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *SetAvatarRequest) GetImageFormat() string {
	if x != nil {
		return x.ImageFormat
	}
	return ""
}

func (x *SetAvatarRequest) GetUseFaceCrop() bool {
	if x != nil {
		return x.UseFaceCrop
	}
	return false
}

type SetAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvatarResponse) Reset() {
	*x = SetAvatarResponse{}
	mi := &file_avatar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvatarResponse) ProtoMessage() {}

func (x *SetAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvatarResponse.ProtoReflect.Descriptor instead.
func (*SetAvatarResponse) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{1}
}

func (x *SetAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetAvatarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_avatar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_avatar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{3}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_avatar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{4}
}

type AvatarInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelName      string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	OutputFps      int32                  `protobuf:"varint,2,opt,name=output_fps,json=outputFps,proto3" json:"output_fps,omitempty"`
	OutputWidth    int32                  `protobuf:"varint,3,opt,name=output_width,json=outputWidth,proto3" json:"output_width,omitempty"`
	OutputHeight   int32                  `protobuf:"varint,4,opt,name=output_height,json=outputHeight,proto3" json:"output_height,omitempty"`
	FramesPerChunk int32                  `protobuf:"varint,5,opt,name=frames_per_chunk,json=framesPerChunk,proto3" json:"frames_per_chunk,omitempty"`
	ChunkDurationS float32                `protobuf:"fixed32,6,opt,name=chunk_duration_s,json=chunkDurationS,proto3" json:"chunk_duration_s,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvatarInfo) Reset() {
	*x = AvatarInfo{}
	mi := &file_avatar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarInfo) ProtoMessage() {}

func (x *AvatarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarInfo.ProtoReflect.Descriptor instead.
func (*AvatarInfo) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{5}
}

func (x *AvatarInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AvatarInfo) GetOutputFps() int32 {
	if x != nil {
		return x.OutputFps
	}
	return 0
}

func (x *AvatarInfo) GetOutputWidth() int32 {
	if x != nil {
		return x.OutputWidth
	}
	return 0
}

func (x *AvatarInfo) GetOutputHeight() int32 {
	if x != nil {
		return x.OutputHeight
	}
	return 0
}

func (x *AvatarInfo) GetFramesPerChunk() int32 {
	if x != nil {
		return x.FramesPerChunk
	}
	return 0
}

func (x *AvatarInfo) GetChunkDurationS() float32 {
	if x != nil {
		return x.ChunkDurationS
	}
	return 0
}

var File_avatar_proto protoreflect.FileDescriptor

const file_avatar_proto_rawDesc = "" +
	"\n" +
	"\favatar.proto\x12\n" +
	"cyberverse\x1a\fcommon.proto\"\x97\x01\n" +
	"\x10SetAvatarRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12!\n" +
	"\fimage_format\x18\x03 \x01(\tR\vimageFormat\x12\"\n" +
	"\ruse_face_crop\x18\x04 \x01(\bR\vuseFaceCrop\"G\n" +
	"\x11SetAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\fResetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\")\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x10\n" +
	"\x0eGetInfoRequest\"\xe6\x01\n" +
	"\n" +
	"AvatarInfo\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"output_fps\x18\x02 \x01(\x05R\toutputFps\x12!\n" +
	"\foutput_width\x18\x03 \x01(\x05R\voutputWidth\x12#\n" +
	"\routput_height\x18\x04 \x01(\x05R\foutputHeight\x12(\n" +
	"\x10frames_per_chunk\x18\x05 \x01(\x05R\x0eframesPerChunk\x12(\n" +
	"\x10chunk_duration_s\x18\x06 \x01(\x02R\x0echunkDurationS2\x9c\x02\n" +
	"\rAvatarService\x12H\n" +
	"\tSetAvatar\x12\x1c.cyberverse.SetAvatarRequest\x1a\x1d.cyberverse.SetAvatarResponse\x12D\n" +
	"\x0eGenerateStream\x12\x16.cyberverse.AudioChunk\x1a\x16.cyberverse.VideoChunk(\x010\x01\x12<\n" +
	"\x05Reset\x12\x18.cyberverse.ResetRequest\x1a\x19.cyberverse.ResetResponse\x12=\n" +
	"\aGetInfo\x12\x1a.cyberverse.GetInfoRequest\x1a\x16.cyberverse.AvatarInfoB*Z(github.com/cyberverse/server/internal/pbb\x06proto3"

var (
	file_avatar_proto_rawDescOnce sync.Once
	file_avatar_proto_rawDescData []byte
)

func file_avatar_proto_rawDescGZIP() []byte {
	file_avatar_proto_rawDescOnce.Do(func() {
		file_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avatar_proto_rawDesc), len(file_avatar_proto_rawDesc)))
	})
	return file_avatar_proto_rawDescData
}

var file_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_avatar_proto_goTypes = []any{
	(*SetAvatarRequest)(nil),  // 0: cyberverse.SetAvatarRequest
	(*SetAvatarResponse)(nil), // 1: cyberverse.SetAvatarResponse
	(*ResetRequest)(nil),      // 2: cyberverse.ResetRequest
	(*ResetResponse)(nil),     // 3: cyberverse.ResetResponse
	(*GetInfoRequest)(nil),    // 4: cyberverse.GetInfoRequest
	(*AvatarInfo)(nil),        // 5: cyberverse.AvatarInfo
	(*AudioChunk)(nil),        // 6: cyberverse.AudioChunk
	(*VideoChunk)(nil),        // 7: cyberverse.VideoChunk
}
var file_avatar_proto_depIdxs = []int32{
	0, // 0: cyberverse.AvatarService.SetAvatar:input_type -> cyberverse.SetAvatarRequest
	6, // 1: cyberverse.AvatarService.GenerateStream:input_type -> cyberverse.AudioChunk
	2, // 2: cyberverse.AvatarService.Reset:input_type -> cyberverse.ResetRequest
	4, // 3: cyberverse.AvatarService.GetInfo:input_type -> cyberverse.GetInfoRequest
	1, // 4: cyberverse.AvatarService.SetAvatar:output_type -> cyberverse.SetAvatarResponse
	7, // 5: cyberverse.AvatarService.GenerateStream:output_type -> cyberverse.VideoChunk
	3, // 6: cyberverse.AvatarService.Reset:output_type -> cyberverse.ResetResponse
	5, // 7: cyberverse.AvatarService.GetInfo:output_type -> cyberverse.AvatarInfo
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avatar_proto_init() }
func file_avatar_proto_init() {
	if File_avatar_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avatar_proto_rawDesc), len(file_avatar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avatar_proto_goTypes,
		DependencyIndexes: file_avatar_proto_depIdxs,
		MessageInfos:      file_avatar_proto_msgTypes,
	}.Build()
	File_avatar_proto = out.File
	file_avatar_proto_goTypes = nil
	file_avatar_proto_depIdxs = nil
}
