// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: tts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{0}
}

func (x *TextChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type ListVoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoicesRequest) Reset() {
	*x = ListVoicesRequest{}
	mi := &file_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoicesRequest) ProtoMessage() {}

func (x *ListVoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoicesRequest.ProtoReflect.Descriptor instead.
func (*ListVoicesRequest) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{1}
}

type ListVoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voices        []*VoiceInfo           `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoicesResponse) Reset() {
	*x = ListVoicesResponse{}
	mi := &file_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoicesResponse) ProtoMessage() {}

func (x *ListVoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoicesResponse.ProtoReflect.Descriptor instead.
func (*ListVoicesResponse) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{2}
}

func (x *ListVoicesResponse) GetVoices() []*VoiceInfo {
	if x != nil {
		return x.Voices
	}
	return nil
}

type VoiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceInfo) Reset() {
	*x = VoiceInfo{}
	mi := &file_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceInfo) ProtoMessage() {}

func (x *VoiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceInfo.ProtoReflect.Descriptor instead.
func (*VoiceInfo) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{3}
}

func (x *VoiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VoiceInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_tts_proto protoreflect.FileDescriptor

const file_tts_proto_rawDesc = "" +
	"\n" +
	"\ttts.proto\x12\n" +
	"cyberverse\x1a\fcommon.proto\":\n" +
	"\tTextChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"\x13\n" +
	"\x11ListVoicesRequest\"C\n" +
	"\x12ListVoicesResponse\x12-\n" +
	"\x06voices\x18\x01 \x03(\v2\x15.cyberverse.VoiceInfoR\x06voices\"K\n" +
	"\tVoiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage2\xa0\x01\n" +
	"\n" +
	"TTSService\x12E\n" +
	"\x10SynthesizeStream\x12\x15.cyberverse.TextChunk\x1a\x16.cyberverse.AudioChunk(\x010\x01\x12K\n" +
	"\n" +
	"ListVoices\x12\x1d.cyberverse.ListVoicesRequest\x1a\x1e.cyberverse.ListVoicesResponseB*Z(github.com/cyberverse/server/internal/pbb\x06proto3"

var (
	file_tts_proto_rawDescOnce sync.Once
	file_tts_proto_rawDescData []byte
)

func file_tts_proto_rawDescGZIP() []byte {
	file_tts_proto_rawDescOnce.Do(func() {
		file_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)))
	})
	return file_tts_proto_rawDescData
}

var file_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tts_proto_goTypes = []any{
	(*TextChunk)(nil),          // 0: cyberverse.TextChunk
	(*ListVoicesRequest)(nil),  // 1: cyberverse.ListVoicesRequest
	(*ListVoicesResponse)(nil), // 2: cyberverse.ListVoicesResponse
	(*VoiceInfo)(nil),          // 3: cyberverse.VoiceInfo
	(*AudioChunk)(nil),         // 4: cyberverse.AudioChunk
}
var file_tts_proto_depIdxs = []int32{
	3, // 0: cyberverse.ListVoicesResponse.voices:type_name -> cyberverse.VoiceInfo
	0, // 1: cyberverse.TTSService.SynthesizeStream:input_type -> cyberverse.TextChunk
	1, // 2: cyberverse.TTSService.ListVoices:input_type -> cyberverse.ListVoicesRequest
	4, // 3: cyberverse.TTSService.SynthesizeStream:output_type -> cyberverse.AudioChunk
	2, // 4: cyberverse.TTSService.ListVoices:output_type -> cyberverse.ListVoicesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tts_proto_init() }
func file_tts_proto_init() {
	if File_tts_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tts_proto_goTypes,
		DependencyIndexes: file_tts_proto_depIdxs,
		MessageInfos:      file_tts_proto_msgTypes,
	}.Build()
	File_tts_proto = out.File
	file_tts_proto_goTypes = nil
	file_tts_proto_depIdxs = nil
}
