// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: voice_llm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceLLMService_Converse_FullMethodName  = "/cyberverse.VoiceLLMService/Converse"
	VoiceLLMService_Interrupt_FullMethodName = "/cyberverse.VoiceLLMService/Interrupt"
)

// VoiceLLMServiceClient is the client API for VoiceLLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceLLMServiceClient interface {
	Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VoiceLLMInput, VoiceLLMOutput], error)
	Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error)
}

type voiceLLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceLLMServiceClient(cc grpc.ClientConnInterface) VoiceLLMServiceClient {
	return &voiceLLMServiceClient{cc}
}

func (c *voiceLLMServiceClient) Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VoiceLLMInput, VoiceLLMOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceLLMService_ServiceDesc.Streams[0], VoiceLLMService_Converse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VoiceLLMInput, VoiceLLMOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceLLMService_ConverseClient = grpc.BidiStreamingClient[VoiceLLMInput, VoiceLLMOutput]

func (c *voiceLLMServiceClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptResponse)
	err := c.cc.Invoke(ctx, VoiceLLMService_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceLLMServiceServer is the server API for VoiceLLMService service.
// All implementations must embed UnimplementedVoiceLLMServiceServer
// for forward compatibility.
type VoiceLLMServiceServer interface {
	Converse(grpc.BidiStreamingServer[VoiceLLMInput, VoiceLLMOutput]) error
	Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error)
	mustEmbedUnimplementedVoiceLLMServiceServer()
}

// UnimplementedVoiceLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceLLMServiceServer struct{}

func (UnimplementedVoiceLLMServiceServer) Converse(grpc.BidiStreamingServer[VoiceLLMInput, VoiceLLMOutput]) error {
	return status.Error(codes.Unimplemented, "method Converse not implemented")
}
func (UnimplementedVoiceLLMServiceServer) Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedVoiceLLMServiceServer) mustEmbedUnimplementedVoiceLLMServiceServer() {}
func (UnimplementedVoiceLLMServiceServer) testEmbeddedByValue()                         {}

// UnsafeVoiceLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceLLMServiceServer will
// result in compilation errors.
type UnsafeVoiceLLMServiceServer interface {
	mustEmbedUnimplementedVoiceLLMServiceServer()
}

func RegisterVoiceLLMServiceServer(s grpc.ServiceRegistrar, srv VoiceLLMServiceServer) {
	// If the following call panics, it indicates UnimplementedVoiceLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceLLMService_ServiceDesc, srv)
}

func _VoiceLLMService_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceLLMServiceServer).Converse(&grpc.GenericServerStream[VoiceLLMInput, VoiceLLMOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceLLMService_ConverseServer = grpc.BidiStreamingServer[VoiceLLMInput, VoiceLLMOutput]

func _VoiceLLMService_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceLLMServiceServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceLLMService_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceLLMServiceServer).Interrupt(ctx, req.(*InterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceLLMService_ServiceDesc is the grpc.ServiceDesc for VoiceLLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceLLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberverse.VoiceLLMService",
	HandlerType: (*VoiceLLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Interrupt",
			Handler:    _VoiceLLMService_Interrupt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converse",
			Handler:       _VoiceLLMService_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voice_llm.proto",
}
