// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: voice_llm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceLLMInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*VoiceLLMInput_Audio
	//	*VoiceLLMInput_Text
	//	*VoiceLLMInput_Config
	Input         isVoiceLLMInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceLLMInput) Reset() {
	*x = VoiceLLMInput{}
	mi := &file_voice_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceLLMInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceLLMInput) ProtoMessage() {}

func (x *VoiceLLMInput) ProtoReflect() protoreflect.Message {
	mi := &file_voice_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceLLMInput.ProtoReflect.Descriptor instead.
func (*VoiceLLMInput) Descriptor() ([]byte, []int) {
	return file_voice_llm_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceLLMInput) GetInput() isVoiceLLMInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *VoiceLLMInput) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Input.(*VoiceLLMInput_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *VoiceLLMInput) GetText() string {
	if x != nil {
		if x, ok := x.Input.(*VoiceLLMInput_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *VoiceLLMInput) GetConfig() *VoiceLLMConfig {
	if x != nil {
		if x, ok := x.Input.(*VoiceLLMInput_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isVoiceLLMInput_Input interface {
	isVoiceLLMInput_Input()
}

type VoiceLLMInput_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,1,opt,name=audio,proto3,oneof"`
}

type VoiceLLMInput_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type VoiceLLMInput_Config struct {
	Config *VoiceLLMConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

func (*VoiceLLMInput_Audio) isVoiceLLMInput_Input() {}

func (*VoiceLLMInput_Text) isVoiceLLMInput_Input() {}

func (*VoiceLLMInput_Config) isVoiceLLMInput_Input() {}

type VoiceLLMOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Audio          *AudioChunk            `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Transcript     string                 `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`
	UserTranscript string                 `protobuf:"bytes,3,opt,name=user_transcript,json=userTranscript,proto3" json:"user_transcript,omitempty"`
	IsFinal        bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoiceLLMOutput) Reset() {
	*x = VoiceLLMOutput{}
	mi := &file_voice_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceLLMOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceLLMOutput) ProtoMessage() {}

func (x *VoiceLLMOutput) ProtoReflect() protoreflect.Message {
	mi := &file_voice_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceLLMOutput.ProtoReflect.Descriptor instead.
func (*VoiceLLMOutput) Descriptor() ([]byte, []int) {
	return file_voice_llm_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceLLMOutput) GetAudio() *AudioChunk {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *VoiceLLMOutput) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *VoiceLLMOutput) GetUserTranscript() string {
	if x != nil {
		return x.UserTranscript
	}
	return ""
}

func (x *VoiceLLMOutput) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type VoiceLLMConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SystemPrompt   string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Voice          string                 `protobuf:"bytes,3,opt,name=voice,proto3" json:"voice,omitempty"`
	Temperature    float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	BotName        string                 `protobuf:"bytes,5,opt,name=bot_name,json=botName,proto3" json:"bot_name,omitempty"`
	SpeakingStyle  string                 `protobuf:"bytes,6,opt,name=speaking_style,json=speakingStyle,proto3" json:"speaking_style,omitempty"`
	WelcomeMessage string                 `protobuf:"bytes,7,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoiceLLMConfig) Reset() {
	*x = VoiceLLMConfig{}
	mi := &file_voice_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceLLMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceLLMConfig) ProtoMessage() {}

func (x *VoiceLLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voice_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceLLMConfig.ProtoReflect.Descriptor instead.
func (*VoiceLLMConfig) Descriptor() ([]byte, []int) {
	return file_voice_llm_proto_rawDescGZIP(), []int{2}
}

func (x *VoiceLLMConfig) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VoiceLLMConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *VoiceLLMConfig) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *VoiceLLMConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *VoiceLLMConfig) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

func (x *VoiceLLMConfig) GetSpeakingStyle() string {
	if x != nil {
		return x.SpeakingStyle
	}
	return ""
}

func (x *VoiceLLMConfig) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

type InterruptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRequest) Reset() {
	*x = InterruptRequest{}
	mi := &file_voice_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRequest) ProtoMessage() {}

func (x *InterruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRequest.ProtoReflect.Descriptor instead.
func (*InterruptRequest) Descriptor() ([]byte, []int) {
	return file_voice_llm_proto_rawDescGZIP(), []int{3}
}

func (x *InterruptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InterruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptResponse) Reset() {
	*x = InterruptResponse{}
	mi := &file_voice_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptResponse) ProtoMessage() {}

func (x *InterruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptResponse.ProtoReflect.Descriptor instead.
func (*InterruptResponse) Descriptor() ([]byte, []int) {
	return file_voice_llm_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_voice_llm_proto protoreflect.FileDescriptor

const file_voice_llm_proto_rawDesc = "" +
	"\n" +
	"\x0fvoice_llm.proto\x12\n" +
	"cyberverse\x1a\fcommon.proto\"\x94\x01\n" +
	"\rVoiceLLMInput\x12.\n" +
	"\x05audio\x18\x01 \x01(\v2\x16.cyberverse.AudioChunkH\x00R\x05audio\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x124\n" +
	"\x06config\x18\x03 \x01(\v2\x1a.cyberverse.VoiceLLMConfigH\x00R\x06configB\a\n" +
	"\x05input\"\xa8\x01\n" +
	"\x0eVoiceLLMOutput\x12,\n" +
	"\x05audio\x18\x01 \x01(\v2\x16.cyberverse.AudioChunkR\x05audio\x12\x1e\n" +
	"\n" +
	"transcript\x18\x02 \x01(\tR\n" +
	"transcript\x12'\n" +
	"\x0fuser_transcript\x18\x03 \x01(\tR\x0euserTranscript\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinalJ\x04\b\x05\x10\x06\"\xf7\x01\n" +
	"\x0eVoiceLLMConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05voice\x18\x03 \x01(\tR\x05voice\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x19\n" +
	"\bbot_name\x18\x05 \x01(\tR\abotName\x12%\n" +
	"\x0espeaking_style\x18\x06 \x01(\tR\rspeakingStyle\x12'\n" +
	"\x0fwelcome_message\x18\a \x01(\tR\x0ewelcomeMessage\"1\n" +
	"\x10InterruptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x11InterruptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa2\x01\n" +
	"\x0fVoiceLLMService\x12E\n" +
	"\bConverse\x12\x19.cyberverse.VoiceLLMInput\x1a\x1a.cyberverse.VoiceLLMOutput(\x010\x01\x12H\n" +
	"\tInterrupt\x12\x1c.cyberverse.InterruptRequest\x1a\x1d.cyberverse.InterruptResponseB*Z(github.com/cyberverse/server/internal/pbb\x06proto3"

var (
	file_voice_llm_proto_rawDescOnce sync.Once
	file_voice_llm_proto_rawDescData []byte
)

func file_voice_llm_proto_rawDescGZIP() []byte {
	file_voice_llm_proto_rawDescOnce.Do(func() {
		file_voice_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_llm_proto_rawDesc), len(file_voice_llm_proto_rawDesc)))
	})
	return file_voice_llm_proto_rawDescData
}

var file_voice_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_voice_llm_proto_goTypes = []any{
	(*VoiceLLMInput)(nil),     // 0: cyberverse.VoiceLLMInput
	(*VoiceLLMOutput)(nil),    // 1: cyberverse.VoiceLLMOutput
	(*VoiceLLMConfig)(nil),    // 2: cyberverse.VoiceLLMConfig
	(*InterruptRequest)(nil),  // 3: cyberverse.InterruptRequest
	(*InterruptResponse)(nil), // 4: cyberverse.InterruptResponse
	(*AudioChunk)(nil),        // 5: cyberverse.AudioChunk
}
var file_voice_llm_proto_depIdxs = []int32{
	5, // 0: cyberverse.VoiceLLMInput.audio:type_name -> cyberverse.AudioChunk
	2, // 1: cyberverse.VoiceLLMInput.config:type_name -> cyberverse.VoiceLLMConfig
	5, // 2: cyberverse.VoiceLLMOutput.audio:type_name -> cyberverse.AudioChunk
	0, // 3: cyberverse.VoiceLLMService.Converse:input_type -> cyberverse.VoiceLLMInput
	3, // 4: cyberverse.VoiceLLMService.Interrupt:input_type -> cyberverse.InterruptRequest
	1, // 5: cyberverse.VoiceLLMService.Converse:output_type -> cyberverse.VoiceLLMOutput
	4, // 6: cyberverse.VoiceLLMService.Interrupt:output_type -> cyberverse.InterruptResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_voice_llm_proto_init() }
func file_voice_llm_proto_init() {
	if File_voice_llm_proto != nil {
		return
	}
	file_common_proto_init()
	file_voice_llm_proto_msgTypes[0].OneofWrappers = []any{
		(*VoiceLLMInput_Audio)(nil),
		(*VoiceLLMInput_Text)(nil),
		(*VoiceLLMInput_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_llm_proto_rawDesc), len(file_voice_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_llm_proto_goTypes,
		DependencyIndexes: file_voice_llm_proto_depIdxs,
		MessageInfos:      file_voice_llm_proto_msgTypes,
	}.Build()
	File_voice_llm_proto = out.File
	file_voice_llm_proto_goTypes = nil
	file_voice_llm_proto_depIdxs = nil
}
